

-- CTES
with 
DADOS_GCP AS (SELECT * FROM application_record_gcp) , 
DADOS_ONPRIMECE AS (SELECT * FROM application_record_local) 
-- Pegar dados não inseridos no GCP
insert into application_record_gcp
SELECT * FROM DADOS_ONPRIMECE ONP 
WHERE NOT EXISTS (SELECT 1 FROM DADOS_GCP GCP WHERE ONP.ID=GCP.ID) ;
-- Jon avaliando difereça de valores entre as tabelas:
SELECT 
A.TABELA, 
A.CODE_GENDER, 
SUM(A.QTDE_CODE_GENDER) QTDE_CODE_GENDER, 
A.FLAG_OWN_CAR, 
SUM(A.QTDE_FLAG_OWN_CAR) QTDE_FLAG_OWN_CAR, 
B.TABELA, 
B.CODE_GENDER, 
SUM(B.QTDE_CODE_GENDER) QTDE_GENDER, 
B.FLAG_OWN_CAR, 
SUM(B.QTDE_FLAG_OWN_CAR) QTDE_FLAG_OWN_CAR 
FROM 
(SELECT 'ONPRIMECE' AS TABELA, ID,CODE_GENDER,COUNT(CODE_GENDER) QTDE_CODE_GENDER,FLAG_OWN_CAR,COUNT(FLAG_OWN_CAR) QTDE_FLAG_OWN_CAR 
FROM DADOS_ONPRIMECE GROUP BY CODE_GENDER,ID,FLAG_OWN_CAR 
) A 
LEFT JOIN (SELECT 'GCP' AS TABELA, ID,CODE_GENDER,COUNT(CODE_GENDER) QTDE_CODE_GENDER,FLAG_OWN_CAR,COUNT(FLAG_OWN_CAR) QTDE_FLAG_OWN_CAR 
FROM DADOS_GCP GROUP BY CODE_GENDER,ID,FLAG_OWN_CAR) B ON A.ID=B.ID 
GROUP BY 
A.TABELA,A.CODE_GENDER,B.TABELA,B.CODE_GENDER
